package au.com.ors.soap.pdv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-14T17:57:18.407+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soap.ors.com.au/pdv", name = "PDVPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PDVPortType {

    @WebResult(name = "PDVCheckResponseMsg", targetNamespace = "http://soap.ors.com.au/pdv", partName = "parameters")
    @Action(input = "urn:PDVCheckRequestMsg", output = "urn:PDVCheckResponseMsg", fault = {})
    @WebMethod(operationName = "PDVCheck", action = "urn:PDVCheckRequestMsg")
    public PDVCheckResponseMsg pdvCheck(
        @WebParam(partName = "parameters", name = "PDVCheckRequestMsg", targetNamespace = "http://soap.ors.com.au/pdv")
        PDVCheckRequestMsg parameters
    ) throws PdvFault_Exception;
}
