
package au.com.ors.soap.crv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-13T12:00:32.388+11:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "CRVFault", targetNamespace = "http://soap.ors.com.au/crv")
public class CRVFault_Exception extends Exception {
    
    private au.com.ors.soap.crv.CRVFault crvFault;

    public CRVFault_Exception() {
        super();
    }
    
    public CRVFault_Exception(String message) {
        super(message);
    }
    
    public CRVFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CRVFault_Exception(String message, au.com.ors.soap.crv.CRVFault crvFault) {
        super(message);
        this.crvFault = crvFault;
    }

    public CRVFault_Exception(String message, au.com.ors.soap.crv.CRVFault crvFault, Throwable cause) {
        super(message, cause);
        this.crvFault = crvFault;
    }

    public au.com.ors.soap.crv.CRVFault getFaultInfo() {
        return this.crvFault;
    }
}
