package au.com.ors.soap.crv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-13T12:00:32.397+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CRVService", 
                  wsdlLocation = "file:/Users/wake/git/soa-REST-BPEL-HRMgmtSys-SOAP/src/main/resources/wsdl/crv.wsdl",
                  targetNamespace = "http://soap.ors.com.au/crv") 
public class CRVService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.ors.com.au/crv", "CRVService");
    public final static QName CRVServiceHttpSoap11Endpoint = new QName("http://soap.ors.com.au/crv", "CRVServiceHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/wake/git/soa-REST-BPEL-HRMgmtSys-SOAP/src/main/resources/wsdl/crv.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CRVService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/wake/git/soa-REST-BPEL-HRMgmtSys-SOAP/src/main/resources/wsdl/crv.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CRVService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CRVService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRVService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CRVPortType
     */
    @WebEndpoint(name = "CRVServiceHttpSoap11Endpoint")
    public CRVPortType getCRVServiceHttpSoap11Endpoint() {
        return super.getPort(CRVServiceHttpSoap11Endpoint, CRVPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRVPortType
     */
    @WebEndpoint(name = "CRVServiceHttpSoap11Endpoint")
    public CRVPortType getCRVServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CRVServiceHttpSoap11Endpoint, CRVPortType.class, features);
    }

}
